import Provider from './components/Provider'
import './globals.css'
import { Inter } from 'next/font/google'
import company from './state'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: `${company.name}`,
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="shortcut icon" href="/images/stock/fav.png" type="image/x-icon" />
      </head>
      <body className={inter.className}>
        <Provider>
          {children}
        </Provider>
      </body>
    </html>
  )
}
